POST http://localhost:8080/add_user
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "username": "test1",
  "name": "Team 1",
  "email": "team@team.team"
}



###
POST http://localhost:8080/buildup
Content-Type: application/json

{
  "username": "team49",
  "apiKey": "XZNYTFQAITSJYCDP"
}


###
POST  http://localhost:8080/privatePage
Content-Type: application/json

{
  "username": "team49",
  "sessionToken": "RVMMKHOMURGJYZAY"
}


###
POST http://localhost:8080/shutdown
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz"
}


###
POST http://localhost:8080/leaderboard
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz"
}


### enable trading
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/buildup
Content-Type: application/json

{
  "username": "team49",
  "apiKey": "TWTSTPBOJVUQVWEX"
}

###
GET http://localhost:8080/get_state

### testing async responses
POST http://localhost:8080/test
Content-Type: application/json

{
  "username": "test1",
  "sessionToken": "test"
}

### Auctions testing
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/set_state
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "targetState": 2
}

###
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/bid_auction
Content-Type: application/json

{
  "username": "team49",
  "sessionToken": "DOVCVQTECFRZPPUS",
  "bid": 0
}


### enable trading
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/set_state
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "targetState": 1
}


### enable trading
POST http://localhost:8080/set_state
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "targetState": 2
}


### enable trading
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/set_state
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "targetState": 1
}


### Settling
POST http://ec2-13-59-143-196.us-east-2.compute.amazonaws.com:8080/set_price
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "prices": {"A": 3, "B": 4, "C": 5}
}

###