POST http://localhost:8080/add_user
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz",
  "username": "test",
  "name": "Team 1",
  "email": "team@team.team"
}



###
POST http://localhost:8080/buildup
Content-Type: application/json

{
  "username": "team49",
  "apiKey": "XZNYTFQAITSJYCDP"
}


###
POST  http://localhost:8080/privatePage
Content-Type: application/json

{
  "username": "team49",
  "sessionToken": "RVMMKHOMURGJYZAY"
}


###
POST http://localhost:8080/shutdown
Content-Type: application/json

{
  "adminUsername": "trading_club_admin",
  "adminPassword": "abcxyz"
}