@host = {{host}}
@adminUsername = {{adminUsername}}
@adminPassword = {{adminPassword}}

###
POST {{host}}/add_user
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "username": "test1",
  "name": "Team 1",
  "email": "team@team.team"
}



###
POST {{host}}/buildup
Content-Type: application/json

{
  "username": "team49",
  "apiKey": "XZNYTFQAITSJYCDP"
}


###
POST  {{host}}/privatePage
Content-Type: application/json

{
  "username": "team49",
  "sessionToken": "RVMMKHOMURGJYZAY"
}


###
POST {{host}}/shutdown
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}"
}


###
POST {{host}}/leaderboard
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}"
}


### enable trading
POST {{host}}/buildup
Content-Type: application/json

{
  "username": "team49",
  "apiKey": "TWTSTPBOJVUQVWEX"
}

###
GET {{host}}/get_state

### testing async responses
POST {{host}}/test
Content-Type: application/json

{
  "username": "test1",
  "sessionToken": "test"
}

### Auctions testing
POST {{host}}/set_state
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "targetState": 2
}

###
POST {{host}}/bid_auction
Content-Type: application/json

{
  "username": "team49",
  "sessionToken": "DOVCVQTECFRZPPUS",
  "bid": 0
}


### enable trading
POST {{host}}/set_state
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "targetState": 1
}


### enable trading
POST {{host}}/set_state
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "targetState": 2
}


### enable trading
POST {{host}}/set_state
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "targetState": 1
}


### Settling
POST {{host}}/set_price
Content-Type: application/json

{
  "adminUsername": "{{adminUsername}}",
  "adminPassword": "{{adminPassword}}",
  "prices": {"A": 3, "B": 4, "C": 5}
}

###